field definition
fieldsDesc 
^ #(
	uint8     			n_d;            
	uint8     			flag;       
	uint16    			op;         
	int     				n_child;    
	int     				tmp;        
	int     				ptr_size;   
	void      			*d;
	int     				ext_label;     
	uint   				ext_flag;      
	void      			*x;             
	void      			*g;             
	void       			*ptr;           
	void       			*gtmp;       
	void 					*child; 
	void 	  				*pre;   
)